# Working with data {#working-with-data}

In many biological projects where large amounts of data from e.g. sequencing are involved, the
project can be divided up into three phases: "annotation", analyses and preparation of final
figures. The quotes around annotation signifies that the term should be understood in a very wide
sense as any kind of processing required before raw data can be turned into a format useful for
the true biological analysis, usually tables but also e.g. sequence files or phylogenies.

![**Overall workflow in computational biology.** The yellow boxes indicate parts that are useful to
keep under version control, e.g. Git. The manuscript is common to keep under a different kind of
source control, the "tracked changes" functionality in word
processors.](img/computational_workflow.png)

The annotation part, although unknown territory when you're new to computational biology, is usually
easier to master than the biological analysis. However, the latter is likely to take much more time
as it's an open-ended exercise without strict roadmap. In other words, you don't know exactly which
analyses to perform and you don't know when you're finished. During this step you are looking for
the "story" that you will eventually tell in the manuscript.

The "Final figures and analyses" is not as separated from the rest of the biological analysis as the
figure above might indicate. In most analyses, you work on the figures and statistical analyses and
with time decide to keep some but not some other. If you work with RMarkdown (see \@ref(rmarkdown))
it is, however, a good practice to create a separate document with the final figures and tables that
will go into the manuscript, including any supplemental material.

## Organizing your work {#organizing-work}

A common way to organize data, code, tables and figures is through spreadsheets. In my mind, this is
very close to *not* organizing.

![**Spreadsheet chaos.** Using spreadsheets often feels convenient, but soon leads to overwhelming
complexity.](img/lucidmanager.20181211.SpreadsheetChaos.jpeg)

(Figure from [The Lucid Manager Blog](https://lucidmanager.org/spreadsheets-for-data-science/).)

```{r include=FALSE}
# vim:tw=100
```
