# Controlling a computer from the command line

## Connecting to other computers with `ssh` {#ssh}

### Public key authentication {#public-key-authentication}

## Users, files, directories and file systems {#users-files-and-filesystems}

### Users, groups and permissions {#users-groups-permissions}

### File systems {#filesystems}

#### Absolute and relative paths {#paths}

### Links {#links}

A *link* is a name of a file and is created with the `ln` command. Links can be either *hard* or
*symbolic* (*symlinks*) and a file can have many. The "normal" name you see for a file is a hard
link.

Links are created with the `ln` command (with the `-s` flag for symlinks), removed with the `rm`
command and moved, including name changed, with `mv`.

#### Hard links {#hard-links}

Every file must have at least one hard link, but can have many, all of them equivalent. This means
that a file can have many indistinguishable names. They must all reside on the same file system (see
\@ref(filesystems)). A file is not removed until you have removed all links. You can see this
behaviour with the following example:

```
pushd /tmp      # cd to /tmp, but remember where I came from
touch l0        # Create an empty file
for i in {1..9}; do ln l0 l${i}; done   # Create 9 more hard links/names
ls -li l[0-9]   # -l is for long and -i shows the inode number
rm l0           # Remove the first created link
ls -li l[0-9]
rm l[0-9]
ls -li l[0-9]
popd            # cd back to where you were before pushd
```

Note that the first column of the file listing above, the *inode number*, is the same for all,
indicating that they point to the same *inode* and that third column of the first listing has a 10:
the number of links. After the first `rm` the number of links goes down to 9. The file does not
disappear until all links have been removed. In actual fact the *inode* remains until the space is
needed, when it can be removed.

#### Symbolic links -- *symlinks* {#symlinks}

A *symlink* can be thought of as a "shortcut" to a hard link. Symlinks can reside on another file
system than the hard link it points to and removing one will never remove the file. For all other
purposes, symlinks are equivalent to hard links and can be very useful.

```
pushd /tmp
touch a_file            # Create an empty file
ln -s a_file a_symlink  # Create a symlink pointing to it
ls -l a_file a_symlink  # List the two
rm a_file a_symlink     # Remove them
popd
```

Note in the row for `a_symlink` in the file listing, that there's an `l` in the first column of the
first field (the permissions) indicating this is a symlink, which is also shown at the end of the
line as `a_symlink -> a_file`.

### Timestamps {#timestamps}

## Using the Linux command line {#linux-cli}

The Linux command line is a program called the *shell*, and exists in different versions. The most
popular is probably `bash` (short for *B*ourne *a*gain *sh*ell) a derivative of the original *Bourne
shell* `sh`. Together with *Korn shell*, `sh` and `bash` forms a family with similar syntax. A
second family started with *C shell* `csh`, which aimed at being more similar in syntax to the *C*
programming language. In this book, we're going to focus solely on `bash`.

The shell is both a way of interacting interactively with the computer and a programming language, a
*scripting* language. When you use the shell interactively you execute commands and programs and a
shell script is nothing else than a set of commands saved for later, though often generalized with
variables etc. to be more useful.

There are many free sources of information available, one of them the classic [Bash Guide for
Beginners](http://www.tldp.org/LDP/Bash-Beginners-Guide/html/) [@garrels_bash_2008] from "The
Linux Documentation Project" (tldp).

### The environment {#bash-environment}

#### Variables {#bash-variables}

#### Configuration files {#bash-config-files}

### Pipelines {#pipelines}

### Job control {#job-control}

`&`, `bg`, `fg`, `jobs` and &lt;ctrl&gt;-Z.

## Screen {#screen}

## Source control with Git {#git}

## Installing programs with Conda {#conda}

Intro.

### How to install Conda {#installing-conda}

Describe both Miniconda and Anaconda.

### How to work with Conda {#working-with-conda}

Short description with links to full documentation.

```{r include=FALSE}
# vim:tw=100
```
