# Regular expressions {#regexps}

\index{regular expression}*Regular expressions*, \index{regexp}*regexps* or
\index{pattern}*patterns*, are strings that describe classes of strings. E.g.  the regexp "Nrd[A-Z]"
describes, or *matches*, the strings "NrdA", "NrdB", "NrdC" or any other string that starts with
"Nrd" and continues with a capital letter. Regexps are used to *search* for strings and in tools
that *modify* strings. 

There are two types of characters in regexps: regular characters and
\index{metacharacter}*metacharacters*. The former makes up the majority and just matches itself;
examples include letters, numbers, space and most other characters. The latter, the metacharacters,
are characters that matches something else than a literal character. Two very common examples are
`.` and `*`. The `.` matches not a \index{literal character}literal character but *any character*,
whereas the `*` is a \index{multiplier}*multiplier* specifying that the character before it could
occur any number of times, including zero. A `.*` pattern hence means "match anything, any number of
times" (which is, of course, rather useless on its own, but is useful when mixed with other
characters).

If you want to search for a literal character, but the specific character, e.g. `.`, is a
metacharacter, you can escape it, usually by preceding it with a `\`. `\.` would hence match a
literal period. In some cases, particularly tools that are older than Perl, such as Grep, Awk and
Sed, there are missing metacharacters. To turn regular characters into metacharacters in these
cases, you have to *escape the regular character*. One example is `(` and `)` which are used in
Perl, and many other regexp engines, to "capture" what was matched for later use, but in standard
sed just means literal parentheses. To capture text and modify it with `sed` you could e.g. write
`s/Nrd\([A-Za-z]\)/Nrd\U\1/` (match "Nrd" followed by any letter and make the letter capital (`\U`:
upper case)). See also the grep alternation example in \@ref(grep)  below.

---------------------------------------------------------------------------------------------------
Metacharacter Meaning                   Examples                                Implemented in 
                                            
------------- ------------------------- --------------------------------------- -------------------
`.`           Match anything.                                                   All

`[a-z]`       Enumeration of characters `[a-z]` matches any small               All
              ("character class").      letter, `[a-zA-Z0-9]` any 
                                        letter or number.
                

`*`           Allow any number of the   `[a-z]*` matches any number             All
              character preceding.      of any small letter.

`?`           Allow one or zero of the  `[a-z]?` matches zero or one            All
              preceding pattern.        small letter.

`+`           At least one.             `[a-z]+` matches one or more            Perl, R. Grep and 
                                        small letters.                          Sed in escaped form.

`^`           Anchor pattern at the     `^NrdA` matches "NrdA" only if it's     All
              start of the line.        at the start of the line.

`$`           Anchor pattern at the     `NrdA$` matches "NrdA" only if it's     All
              end of the line.          at the end of the line.

`(n)`         Capture and group.        Capture for later use in a              Perl, R. Grep and 
                                        substitution (see Sed below)            Sed in escaped form.
                                        or group used with the                  
                                        alternation character `|`.

`|`           Alternation.              Match either what's before the pipe     Perl, R. Grep and
                                        or what comes after (usually in         Sed in escaped form.
                                        parentheses, i.e `(bike)|(boat)`.       

`&`           In *substitution*:        `s/(Nrd[A-Z])/&\t&/` duplicates the     All that have
              whatever was matched      match separated with a tab.             substitution: Perl,
                                                                                Sed, R.

`\1`          In *substitution*:        `s/.*(Nrd[A-Z])/\1/` strip off          All that have
              whatever was matched by   anything before "Nrdx". Up to nine      substitution.
              first set of parentheses. pairs of parentheses can be used.

---------------------------------------------------------------------------------------------------

Table: (\#tab:regexp-metacharacters) Common metacharacters used in regular expressions.

Below, a few tools that implement regexps are described.

## Grep {#grep}

The \index{Grep}Grep program^[Supposedly, "grep" stands for "**G**lobally search a **R**egular
**E**xpression and **P**rint".] is a standard UNIX search tool commonly used on its own or in
pipelines to search for *lines* in files that contain a regexp. That Grep searches for lines instead
of only the search pattern -- unless you specify the `-o/--only-matching` option -- makes it a
little bit different than most other tools since you do not have to specify a complete,
line-matching, pattern, but just a piece that is sufficiently discriminating. Grep is a tool that is
commonly used as a filter in pipelines see \@ref(pipelines) and the examples below.

---------------------------------------------------------------------------------------------------
Options                 Meaning                 
----------------------- ---------------------------------------------------------------------------
-i/--ignore-case        Ignore case, i.e. look for matches disregarding capital/lower case.

-v/--invert-match       Invert match, i.e. output lines that do *not* match the pattern.

-c/--count              Count the number of matching lines.

-f FILE/--file=FILE     Search for patterns specified in FILE.

-l/--files-with-matches Output only the names of files containing at least one matching line.

---------------------------------------------------------------------------------------------------

Table: (\#tab:grep-options) Commonly used options in Grep. See the manual page for much more.

Some examples of how to use Grep:

```
# Search for a user named "dl" in the user database
grep dl /etc/passwd

# Search for RNR proteins in a fasta file containing NCBI's NR database
# (The quotes are not necessary, but a good habit to make sure regexps not
# mistakenly match file globs.)
grep "Nrd[ABDEFJ]" nr.faa

# Subset results to mouse and human, assuming the species name comes after the 
# protein name.
# This pattern uses *alternation* when looking for either mouse or human.
# (The parentheses and pipe are not metacharacters in grep, so we have to escape 
# them.)
grep "Nrd[ABDEFJ].*\(Mus musculus\)\|\(Homo sapiens\)" nr.faa

# If we're not certain that protein name comes before species, build a pipeline
grep "Nrd[ABDEFJ]" nr.faa | grep "\(Mus musculus\)\|\(Homo sapiens\)"
```

(The above describes Grep's *basic regular expression* mode (BRE), which is the default. There is
also an *extended regular expression* mode (ERE) which is available via the `-E` option.)

## Sed {#sed}

\index{Sed}Sed^[Sed stands for **S**tream **ED**itor.] is a tool that uses regexps to modify text.
The most common way to use the program is to specify a substitution command that looks like
`s/regexp/replacement/` which is like a search (regexp) and replace (replacement) command, but more
powerful. In the replacement part, you can refer to the whole match (`&`) or parts of the match that
were captured with parentheses (`\1`). After the last `/` you can add modifiers; the most commonly
used is `g` (global) which does more than one replacement per line.

Like Grep, Sed is a very powerful pipeline tool.

Some examples of how to use Sed:

```
# Replace space with underscore characters:
sed "s/ /_/g" file > newfile

# If there sometimes are more than one space that you want to replace with a single underscore:
sed "s/ \+/_/g" file > newfile

# The -i option edits the file in place
sed -i "s/ \+/_/g" file > newfile
```

More help can be found at the [GNU Sed home page](http://www.gnu.org/software/sed/) or by searching
the Internet.

## AWK {#awk-regexps}

\index{AWK}AWK is a complete programming language with a feature complete regexp engine. Although
not much used for script writing anymore, it is a popular tool in pipelines. Since its regexp engine
is rarely seen in pipelines I'm skipping it here for now.

## Perl {#perl-regexps}

The \index{Perl}Perl scripting language has meant more for the development of regexps than any other
language with the invention of several new useful concepts like metacharacters for predefined
character classes like numbers and whitespace. Since Perl unfortunately has lost most of its early
user base in computational biology, I'm not going to describe it here.

## R {#r-regexps}

\index{R}R has a very complete regexp engine. One primarily uses the `grep` family of functions for
regexps in R: `grep` and `grepl` for matching, i.e. searching, `sub` and `gsub` for substituation
(the former does *one* substituation, the latter global, i.e. as many substitutions as possible) and
`regexp`, `gregexp` and `regexec` for some other operations (see help for any of the mentioned
functions).  There are also other functions that use regexps, e.g. the excellent `stringr` package
(part of the Tidyverse).

One quirk with R is that escaping regexp characters needs *double `\` characters*, i.e. use `\\`
whenever you would use `\`, see examples below.

Some examples, in a \index{Tidyverse}Tidyverse setting:

```
# Replace space with underscore characters:
data <- data %>% mutate(f = gsub(' +', '_', f))

# Cutout everything except "Nrd[A-Z" from a string
data <- data %>% mutate(f = sub('.*(Nrd[A-Z]).*', '\\1', f))

# Assign a class to rows where the protein name matches 'Nrd[ABDEFJ]'
data <- data %>% 
  mutate(
    class = case_when(
      grepl('Nrd[ABEF]', protein) ~ 'I',
      grepl('NrdD', protein)      ~ 'III',
      grepl('NrdJ', protein)      ~ 'II',
      TRUE                        ~ 'Unknown'
    )
  )
```

## Vim {#vim-regexps}

One of the things that makes \index{Vim}Vim such a powerful \index{text editor}\index{editor}text
editor is its use of regexps. You can *search* for regexps by pressing `/` (forward search) or `?`
(backward), typing a regexp and pressing &lt;Enter&gt; (pressing `n` will repeat the search, i.e.
search for the next occurrence; pressing `N` searches in the reverse direction).

You can also modify text using regexps and the builtin in \index{Ed}Ed line editor which is accessed
by pressing `:`. Ed is rather similar to \index{Sed}Sed (\@ref(sed)). Each command starts with a
specification of which lines to operate on. `%` means the whole file, `1,10` lines 1-10, `.,+4` the
current line plus four more. You can use regexps for this too. `g/Nrd[A-Z]/` will operate on all
lines containing "Nrd[A-Z]", and `v/Nrd[A-Z]` on lines that do *not* contain "Nrd[A-Z]". After the
"address", i.e. which lines to operate on, comes a command which often is a substitution in the same
shape as Sed, i.e. `s/pattern/something/`, possibly with a modifier like `g` (global, i.e. all
possible places) added `s/pattern/something/g`. A few example commands to try in Vim:

```
# On this line, and the two below, replace literal "global" with "local", but only once
:.,+2s/global/local/
# On all lines, replace all "Nrd[A-Z]" in all kinds of capitalizations with the 
# correctly capitalized
:%s/nrd\([a-z]\)/Nrd\U\1/ig
```

In the [intro guide to Vim](https://www.linux.com/learn/vim-101-beginners-guide-vim) I linked to in
the Vim section (\@ref(vim)), there's a very short intro to the Ed commands. When you want to know
more, Google or check the man page for Ed: `man ed`.

## More and Less {#more-regexps}

The \index{More}More and \index{Less}Less "pagers", i.e. programs that allow you to study a
\index{text file}text file page by page, allow you to search for regexps similar to Vim, i.e. by
first pressing `/` (forward search) or `?` (backward).

```{r include=FALSE}
# vim:tw=100
```
