# Alphabetical list of Bash commands

Below, some commands are listed in alphabetical order with very little detail, see the `man` pages
for more information (see \@ref(cli-getting-help)) or Google.

- `&`: Place after a command to direct it to background execution. See \@ref(job-control).

- &lt;ctrl&gt;-Z: Background a running program. See \@ref(job-control).

- `bg`: Background a stopped program; see also `fg` and `jobs`. See \@ref(job-control).

- `cat`: Print one or more files to STDOUT. Often used to concatenate several files to create a
  single file: `cat file1 file2 file3 > new_file`. See \@ref(pipelines).

- `cd`: Change directory

- `chgrp`: Change user (and group). See \@ref(users-groups-permissions).

- `chmod`: Change permissions of a file or directory. See \@ref(users-groups-permissions).

- `chown`: Change owner of a file or directory. See \@ref(users-groups-permissions).

- `fg`: Foreground a running program. See \@ref(job-control).

- `find`: Searches for files. Very powerful, takes a little while to learn and a lifetime to
  master... Look for simple examples on the web before you take on the man page.

- `grep`: Search for text patterns, i.e. *regular expressions*, see \@ref(regexps) and \@ref(grep).

- `jobs`: List programs with their state. See \@ref(job-control).

- `less`: More modern reimplementation of `more`, see below.

- `ln`: Creates links, almost exclusively used with the `-s`(ymbolic) flag, which creates a
  *symlink*. See \@ref(links).

- `ls`: List directory, often used with the `-l`(ong) flag (common alias: `ll`)

- `man`: Read a manual ("man") page. The only required argument is the name of the command or
  program, e.g. `man find`. See \@ref(cli-getting-help).

- `more`: Command that lets you read output page by page. The only required argument is the name of
  a file; often used in pipelines (see \@ref(pipelines)). `less` is similar.

- `mkdir`: Make directory, often used with the `-p`(arents) flag which can
  create any non-existing parent directories

- `mv`: Move a file; includes changing the name. Moving between directories within a file system is
  just renaming the file, moving between file systems actually moves data and hence takes much
  longer.

- `popd`: Move back one directory by removing the top directory in the stack; see also `pushd`.
  
- `pushd`: Move to a directory and place it in a *stack* of directories; see also `popd`. 

- `pwd`: Print working directory, i.e. show which directory you're "standing" in.

- `rm`: Remove a file, or, to be strict, a link (see \@ref(links)). The last hard link to be
  removed, removes the file.

- `touch`: Change any timestamp of a file, in most cases the *modified* timestamp (see
  \@ref(timestamps)). `touch` is commonly used to create an empty file: `$touch empty_file`.

```{r include=FALSE}
# vim:tw=100
```
